### ISSUE TITLE
Loading "obfuscator.js" tasks...ERROR

### ISSUE THREAD

**Issue by RohanSakhale** [javascript-obfuscator/grunt-contrib-obfuscator#1]
Locally this is working perfectly on Windows machine but giving error "ReferenceError: Map is not defined" when running on GitLab CI using Docker "[saiashirwadinformatia/php-node:v1](https://hub.docker.com/r/saiashirwadinformatia/php-node/)"

Build output

```
$ grunt
Loading "obfuscator.js" tasks...ERROR
>> ReferenceError: Map is not defined
Warning: Task "obfuscator" not found. Use --force to continue.

Aborted due to warnings.
ERROR: Build failed: exit code 1
```

**Comment by sanex3339** [comment]
What Node version installed with `saiashirwadinformatia/php-node:v`?

`javascript-obfuscator` supports only node 4+

**Comment by RohanSakhale** [comment]
Exactly, node installed using `apt-get install nodejs` is quite old, rebuilded docker from node and everything is working fine. Thanks for pointing out the issue.

**Comment by pegues** [comment]
I'm getting an error through Task Runner Explorer with Visual Studio for obfuscator. It says:

>> Loading "ubfuscator.js" tasks...ERROR
>> ReferenceError: Symbol is not defined

If running "grunt" from bash shell, everything works fine and no error is displayed.

Any suggestions?
