### ISSUE TITLE
Update obfuscator version to `1.8.0`

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/grunt-contrib-obfuscator#22]
Hi. Please update obfuscator version to `1.8.0`

**Comment by slig** [comment]
Hi,

Since the `javascript-obfuscator` dependency is listed as a peerDependency, do we still have to update the version number on the package.json?

**Comment by sanex3339** [comment]
It described both in `dependency` and `peerDependency` sections

**Comment by slig** [comment]
You're right!

Since I'm going to update it now, is it better to remove the `dependency` entry and leave only the `peerDependency` one?

**Comment by sanex3339** [comment]
Yes. And update required version inside `peerDependency` section to `1.8.0`

**Comment by slig** [comment]
Done!

**Comment by sanex3339** [comment]
Thank you!

**Comment by slig** [comment]
You're welcome!
