### ISSUE TITLE
Option Banner is not working

### ISSUE THREAD

**Issue by Sinanqd10** [javascript-obfuscator/grunt-contrib-obfuscator#4]
I have tried the option
obfuscator: {
        options: {
            banner: '//obfuscated with grunt-contrib-obfuscator.\n'
        },
        files: [            
            'src/*.js'
        ],
        entry: 'src/*.js',
        out: 'build/app.min.js',
        strings: true,
        root: __dirname
    }
but it doesn't output the commend banner

**Comment by slig** [comment]
Thanks for filling in the issue!

Currently I can't investigate this bug, it'll have to wait as the core functionality still works.

**Comment by rvalitov** [comment]
This issue should be closed, because the banner option works correctly with all recent versions of `javascript-obfuscator` (at least since 0.18.x).
