### ISSUE TITLE
Update javascript-obfuscator to 0.11.1

### ISSUE THREAD

**Issue by orion110217** [javascript-obfuscator/grunt-contrib-obfuscator#5]
Hi, I'm hitting a Illegal return statement which is fixed in 0.11.1 of javascript-obfuscator. I think updating will fix the problem.

**Comment by sanex3339** [comment]
Also latest version 0.14.3

**Comment by slig** [comment]
I will try to update this weekend.

**Comment by sanojian** [comment]
javascript-obfuscator is all the way up to 0.18.0 and there are a lots of bugs in the 0.10.0 version that have been fixed.   Any chance this can be updated?

**Comment by sanex3339** [comment]
Right now it's better to update to 0.17.3. because of 0.18.* is quite unstable and i'll fix bugs only next month.

**Comment by sanex3339** [comment]
Updated
