### ISSUE TITLE
Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class

### ISSUE THREAD

**Issue by 30dnh01** [javascript-obfuscator/grunt-contrib-obfuscator#9]
with latest version of node js (13.5) grunt-contrib-obfuscator raises the following error :

Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class

the same settings with node v12.4.0 works perfectly well...

help?

**Comment by sanex3339** [comment]
Hi. Already fixed in https://github.com/javascript-obfuscator/javascript-obfuscator/issues/452

Expect the release this weekend

**Comment by stijnherreman** [comment]
I've tried updating javascript-obfuscator to 0.24.6 but grunt-contrib-obfuscator insists on using 0.10.2
Is there anything else I should to in order to get this error resolved?

**Comment by sanex3339** [comment]
@slig can you publish a new version?

**Comment by slig** [comment]
Should I move the `javascript-obfuscator` to a peerDependency or keep it as it is? currently it's `"javascript-obfuscator": "^0.23.2"`.

**Comment by sanex3339** [comment]
Hmm. You can set it as `peerDependency` and describe it in the README

**Comment by slig** [comment]
Done!

**Comment by stijnherreman** [comment]
Thank you! Can confirm the new 5.0.0 version works fine.
